[package]
name = "logging"
version = "0.1.0"
authors = ["Cassidy Marble"]
edition = "2021"

[dependencies.simplelog]
version = "0.11"

[dependencies.log]
version = "0.4"
features = ["max_level_trace", "release_max_level_warn"]
