[package]
name = "git-bindings"
version = "0.1.0"
authors = ["Cassidy Marble"]
edition = "2021"

[dependencies]
git2 = "0.13"

[dependencies.log]
version = "0.4"
features = ["max_level_debug", "release_max_level_warn"]
