[package]
name = "util"
version = "0.1.0"
authors = ["Cassidy Marble <marblenix@users.noreply.github.com>"]
edition = "2018"

[dependencies]
git2 = "0.13"
simplelog = "0.10"

[dependencies.log]
version = "0.4"
features = ["max_level_trace", "release_max_level_warn"]
