[package]
name = "prepare-commit-msg"
version = "0.1.0"
authors = ["Cassidy Marble"]
edition = "2018"

[dependencies]
git2 = "0.13"
util = { path = "../util" }

[dependencies.log]
version = "0.4"
features = ["max_level_debug", "release_max_level_warn"]
