[package]
name = "prepare-commit-msg"
version = "0.1.0"
authors = ["Cassidy Marble"]
edition = "2021"

[dependencies.git-bindings]
path = "../git-bindings"

[dependencies.logging]
path = "../logging"

[dependencies]
regex = "1"
