[package]
name = "prepare-commit-msg"
version = "0.1.0"
authors = ["Cassidy Marble"]
edition = "2021"

[dependencies.git-bindings]
path = "../git-bindings"

[dependencies.regex]
version = "1"

[dependencies.log]
version = "0.4"
features = ["max_level_debug", "release_max_level_warn"]
